---
title: "2018-10-24"
output: html_notebook
---
```{r}

```


```{r}
library(googlesheets)
```

```{r}
gs_auth(new_user = TRUE)
```

```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
class(classSurvey)
```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
stringsAsFactors=F
```

```{r}
names(StuDF) 
colnames(StuDF)
```

```{r}
StuDF[1,2]
StuDF[,2]
StuDF[1,]
StuDF[c(1,4),]
StuDF[c(1,4),c(2,3)]
```

```{r}
StuDF[c(1,4),]
StuDF[-c(1,4),]
```

```{r}
c(1:3) # same as c(1,2,3)
c(5:7) # same as c(5,6,7)
c(1,5:7,10) #same as c(1,5,6,7,10)
```

```{r}
StuDF[c(T,F,F,F,F),c(F,T,F)]
StuDF[c(T,F,F,T,F),]
```

```{r}
StuDF [1,4]
StuDF[c(T,F,F,T,F),]
```

```{r}
a<-c(T,T,F,F,T,F,F)
sum(a)
```

```{r}
(StuDF$score >= 80)
(StuDF$name == "小新")
```

找出StuDF分數大於等於80的人名。
找出小新的分數。
```{r}
StuDF[c(StuDF$score >= 80),2]
```

```{r}
library(googlesheets)
```

```{r}
gs_auth(new_user = TRUE)
```

```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
class(classSurvey)
```

```{r}
(classSurvey$性別 == "男")

(classSurvey$本學期學分數 > 20)

(classSurvey$性別 == "男" | 
    classSurvey$本學期學分數 > 20)
```

```{r}
classSurvey[
  $性別 == "男" )
(classSurvey$本學期學分數 > 26)
3
```

```{r}
aaa<-c(3,7,9,10)
```

```{r}
StuDF$StuID
StuDF[,c("StuID")]
StuDF$name
StuDF[,c("name")]
```

```{r}
StuDF[,c("StuID","name")]

## 無法用$一次取兩個元素
# StuDF$c("StuID","name")
```

```{r}
StuDF[c(1,4),c(2)]
StuDF[,c(2)][c(1,4)]

StuDF[,c(2)] -> aa
aa[c(1,4)] 
```
            
```{r}
StuDF[`names<-`()]
```

```{r}
StuDF[,c(1,3)][c(1,4)]

```

