---
title: "2018-12-05"
output: html_notebook
---
```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
```


```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData %>% 
  mutate_at(
  vars(學院,書籍館藏地,書籍類別)
  funs(
  as.factor(.)    
  )
)->libraryData

libraryData %>%
mutate(
   借閱時間=ymd_hms(借閱時間,tz="Asia/Taipei")
) -> libraryData

```

```{r}
## 1
max(libraryData$讀者借閱冊數)-> maxNumber
min(libraryData$讀者借閱冊數)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)

## 2
max(libraryData$入學年)-> maxNumber
min(libraryData$入學年)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)

## 3
max(libraryData$書籍上架年月)-> maxNumber
min(libraryData$書籍上架年月)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
```

minMaxFun(x)
```{r}
minMaxFun <- function(x){
  max(x)-> maxNumber
  min(x)-> minNumber
  paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
}
```

```{r}
minMaxFun2 <- function(x){
  max(x)-> maxNumber
  min(x)-> minNumber
  paste0("最大值： ",maxNumber, " 最小值： ",minNumber)->result
  return(result)
}

```

```{r}
minMaxFun3 <- function(x){
  max(x)-> maxNumber
  min(x)-> minNumber
  paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
  return(maxNumber)
}
```

```{r}
minMaxFun(libraryData$讀者借閱冊數)
minMaxFun(libraryData$入學年)
minMaxFun(libraryData$書籍上架年月)
```

```{r}
minMaxFun4(libraryData$讀者借閱冊數) -> a1
a1
```
###PRACTICE
```{r}
!is.numeric(libraryData$學號)
!is.numeric(libraryData$書籍類別)
```

```{r}
not_numeric <- function(x){
  !is.numeric(x)
}
```

```{r}
not_numeric <- function(x){
  !is.numeric(x)-> result
  return(result)
}
```

```{r}
not_numeric(libraryData$學號)
```

###PRACTICE
```{r}
(libraryData$學院=="人文學院") -> logIndex
libraryData[logIndex,] -> subsample
```

```{r}
(libraryData$學院=="社會科學院") -> logIndex
libraryData[logIndex,] -> subsample1
```

```{r}
findMycollege <- function(x){
  (libraryData$學院=="社會科學院") -> logIndex
libraryData[logIndex,] -> subsample2
return(subsample)
}
```

```{r}
findMycollege("人文學院")->subsample1
nrow(subsample1)
findMycollege("社會科學院")->subsample2
nrow(subsample2)
```

```{r}
libraryData %>%
  group_by(學院) %>%
  summarize(
    學院借閱冊數=length(學號)
  )
```


```{r}
libraryData %>%
  select(讀者借閱冊數,書籍出版日期) %>%
  summarise(
    讀者平均借閱冊數=mean(讀者借閱冊數),
    最小書籍出版日期=min(書籍出版日期,na.rm=T),
    最大書籍出版日期=max(書籍出版日期,na.rm=T)
  )
```

```{r}
library(readr)
transcriptData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcript100_102.csv")
```

