---
title: "2018-12-12"
output: html_notebook
---

```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$書籍館藏地 %>% as.factor %>% levels -> storageLocations
storageLocations
```

```{r}
libraryData$書籍館藏地 <-
  as.factor(libraryData$書籍館藏地)
levels(libraryData$書籍館藏地) -> storageLocations
```

```{r}
allBorrowCount <- vector("numeric",18)

i<-1
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```

```{r}
libraryData$學院 %>% as.factor %>% levels -> college
#0 
collegeBorrowCount <- vector("numeric",length(college))
for(i in c(1:length(college))){
#1
college_i <- college[i]
#2
numericalIndexForSubsample<-which(libraryData$學院 == college_i)
collegesubsample_i <- libraryData[numericalIndexForSubsample,]
#3
collegeBorrowCount_i <- nrow(collegesubsample_i)
#4
collegeBorrowCount[[i]]<-collegeBorrowCount_i }
```

```{r}
libraryData$學號 %>% as.factor %>% levels -> student
studentBorrow <- vector("numeric", length(student))
for(i in c(1:length(student))){
student_i <- student[i]
numericalIndex <- which(libraryData$學號 == student_i)
studentSubsample_i <- libraryData[numericalIndex,]
studentBorrow_i <- nrow(studentSubsample_i)
studentBorrow[[i]] <- studentBorrow_i
}
```

```{r}
libraryData %>%
  group_by(書籍館藏地) %>%
  summarise(
    borrowCount=length(學號) 
  ) -> result
result
```

```{r}
libraryData %>%
  mutate(
    學系=str_sub(學號,5,6)
  ) ->libraryData
```

```{r}
libraryData %>%
  group_by(學院,入學年) %>%
  summarise(
    borrowCount=length(學號)
  ) %>%
  ungroup-> result2
result2
```

```{r}
#0 container

for(i in seq_along(college)){
  for(j in seq_along(entranceyear))
   }
```

```{r}

```

